### ISSUE TITLE
Puzzles on Shadow

### ISSUE THREAD

**Issue by kingsleyluoxin** [toshipiazza/drtaint#8]
I have been wondering what makes the differences between operating directly on memory and that on shadow memory. Will it be available to directly do dynamic taint analysis on memory or registers?

**Comment by toshipiazza** [comment]
Sorry about the late reply. Hopefully this answers the question:

Using DynamoRIO you can modify real memory, and building your client with this plugin will also allocate shadow memory for you and allow you to modify it. This shadow memory is where the taint info is currently stored. To reiterate, this plugin performs taint analysis on real memory and registers, and keeps associated taint values in shadow memory/regs.

**Comment by kingsleyluoxin** [comment]
Thanks so much for your detailed reply!
